# Bibliothek Laden

In [1]:
# Bilbiothek importieren
import torch
import numpy as np

# Erstellen von Tensoren mit PyTorch

In [2]:
# creating an empty tensor
x = torch.empty(size = (3,2), dtype=torch.float16) # 3 rows, 2 columns
display("empty tensor", x)
display("empty tensor dtype", x.dtype)
display("empty tensor size", x.size()) # tensor.size() using method

# creating a tensor with random values
x = torch.rand(size = (2,3))
display("random tensor", x)

# analog to np.zeros and np.ones, np.eye
x = torch.zeros(size = (2,2))
display("zero tensor", x)

x = torch.ones(size = (2,4))
display("ones tensor", x)

x = torch.eye(n = 3)
display("eye tensor", x)

# create from a pyhon list
python_list = [1,2,3,4,5,6]
x = torch.tensor(python_list)
display("tensor from python list", x)

# addition von tensoren
x = torch.eye(n=2)
y = torch.eye(n=2)


'empty tensor'

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float16)

'empty tensor dtype'

torch.float16

'empty tensor size'

torch.Size([3, 2])

'random tensor'

tensor([[0.8184, 0.5808, 0.7959],
        [0.2097, 0.0314, 0.7060]])

'zero tensor'

tensor([[0., 0.],
        [0., 0.]])

'ones tensor'

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

'eye tensor'

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

'tensor from python list'

tensor([1, 2, 3, 4, 5, 6])

# Berechnungen mit Tensoren

In [3]:
# addition von tensoren
x = torch.eye(n=2)
y = torch.eye(n=2)

z = x + y # torch.add(x,y)
display("addition of tensors", z)
display("addition of tensors", y.add(10))

# inplace operationen enden immer mit _ (inplace y)
y.add_(x)
display("inplaced y tenor", y)

# subtraktion von tensoren
display("substraktion von tensoren", torch.sub(x,y))

# elementweise multiplication
x = torch.tensor(np.array([[1,2,3],[4,5,6]]))
y = torch.tensor(np.array([[1,2,3],[4,5,6]]))
z = torch.mul(x,y)
display("elementweise multiplication", z)
display("elementweise multiplication with 2", torch.mul(x, 100))

# elementweise division
display("elementweise division", torch.div(x,y))

# matrix multiplikation von tensoren
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[1,2],[3,4],[5,6]])
z = torch.matmul(x,y)
display("matrix multiplication", z)


'addition of tensors'

tensor([[2., 0.],
        [0., 2.]])

'addition of tensors'

tensor([[11., 10.],
        [10., 11.]])

'inplaced y tenor'

tensor([[2., 0.],
        [0., 2.]])

'substraktion von tensoren'

tensor([[-1.,  0.],
        [ 0., -1.]])

'elementweise multiplication'

tensor([[ 1,  4,  9],
        [16, 25, 36]], dtype=torch.int32)

'elementweise multiplication with 2'

tensor([[100, 200, 300],
        [400, 500, 600]], dtype=torch.int32)

'elementweise division'

tensor([[1., 1., 1.],
        [1., 1., 1.]])

'matrix multiplication'

tensor([[22, 28],
        [49, 64]])

# Slicing von Tensoren

In [4]:
x = torch.rand(size = (5,3), dtype=torch.float32)
display("x", x)

# selektieren von zeilen
display("x[0:2]", x[0:2 , :])

# selektieren von spalten
display("x[:,0]", x[: , 0:2])

# selektieren von zeilen und spalten
display("x[2:4,0:2]", x[2:4 , 0:2])

'x'

tensor([[0.6684, 0.7884, 0.6627],
        [0.7317, 0.6432, 0.1939],
        [0.3530, 0.6339, 0.7837],
        [0.9182, 0.4334, 0.8664],
        [0.0772, 0.2753, 0.5576]])

'x[0:2]'

tensor([[0.6684, 0.7884, 0.6627],
        [0.7317, 0.6432, 0.1939]])

'x[:,0]'

tensor([[0.6684, 0.7884],
        [0.7317, 0.6432],
        [0.3530, 0.6339],
        [0.9182, 0.4334],
        [0.0772, 0.2753]])

'x[2:4,0:2]'

tensor([[0.3530, 0.6339],
        [0.9182, 0.4334]])

# Reshaping von Tensoren

In [5]:
x = torch.rand(size = (4,4), dtype=torch.float32)
display("x", x)

# mittels torch.view() Dimension aendern
display("1D array", x.view(16))

# 2D array
display("2D array", x.view(8,2))

# nutzen von -1, (torch findet die passende Dimension selbst heraus)
display("2D array", x.view(-1,8))
display("2D array", x.view(8,-1))

'x'

tensor([[0.4036, 0.5932, 0.8789, 0.9194],
        [0.9720, 0.2617, 0.1824, 0.3583],
        [0.9047, 0.0191, 0.3272, 0.1208],
        [0.1484, 0.9238, 0.0778, 0.0094]])

'1D array'

tensor([0.4036, 0.5932, 0.8789, 0.9194, 0.9720, 0.2617, 0.1824, 0.3583, 0.9047,
        0.0191, 0.3272, 0.1208, 0.1484, 0.9238, 0.0778, 0.0094])

'2D array'

tensor([[0.4036, 0.5932],
        [0.8789, 0.9194],
        [0.9720, 0.2617],
        [0.1824, 0.3583],
        [0.9047, 0.0191],
        [0.3272, 0.1208],
        [0.1484, 0.9238],
        [0.0778, 0.0094]])

'2D array'

tensor([[0.4036, 0.5932, 0.8789, 0.9194, 0.9720, 0.2617, 0.1824, 0.3583],
        [0.9047, 0.0191, 0.3272, 0.1208, 0.1484, 0.9238, 0.0778, 0.0094]])

'2D array'

tensor([[0.4036, 0.5932],
        [0.8789, 0.9194],
        [0.9720, 0.2617],
        [0.1824, 0.3583],
        [0.9047, 0.0191],
        [0.3272, 0.1208],
        [0.1484, 0.9238],
        [0.0778, 0.0094]])

# requires_grad 

In [6]:
# erstelle einen Tensor
x = torch.rand(size = (4,4), dtype=torch.float32, requires_grad=True)
display("x", x)

# fuer was ist requires_grad?
# requires_grad=True, erlaubt es, die Gradienten zu berechnen
# fuer was ist das gut?
# Gradienten sind wichtig fuer das Training von neuronalen Netzen

'x'

tensor([[0.4802, 0.0535, 0.4527, 0.3083],
        [0.1114, 0.9058, 0.7951, 0.0387],
        [0.8500, 0.8339, 0.3248, 0.7115],
        [0.7505, 0.2645, 0.8783, 0.8795]], requires_grad=True)